# Generated by Django 4.1 on 2024-06-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='ttnumber',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
