# Generated by Django 4.1 on 2024-09-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0002_moviereview_delete_watcheddates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviereview',
            options={'verbose_name_plural': 'Movie Reviews'},
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
