# Generated by Django 4.1 on 2024-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0003_alter_moviereview_options_alter_moviereview_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='enjoyment',
            field=models.DecimalField(blank=True, choices=[(0, '0: dislike'), (0.5, '0.5'), (1, '1: mweh'), (1.5, '1.5'), (2, '2: fun'), (2.5, '2.5'), (3, '3: good / cool'), (3.5, '3.5'), (4, '4: great')], decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='quality',
            field=models.DecimalField(blank=True, choices=[(0, '0: bad, not worth watching'), (0.5, '0.5'), (1, '1: bad, but interesting'), (1.5, '1.5'), (2, '2: good enough'), (2.5, '2.5'), (3, '3: good'), (3.5, '3.5'), (4, '4: great')], decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='watch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviestatus',
            name='netflix',
            field=models.BooleanField(blank=True, choices=[(None, 'unknown'), (True, 'available'), (False, 'not available')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='moviestatus',
            name='prime',
            field=models.BooleanField(blank=True, choices=[(None, 'unknown'), (True, 'available'), (False, 'not available')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='moviestatus',
            name='priority',
            field=models.BooleanField(blank=True, choices=[(True, 'yes'), (False, 'no')], default=False),
        ),
        migrations.AlterField(
            model_name='moviestatus',
            name='status',
            field=models.BooleanField(blank=True, choices=[(None, 'unknown'), (True, 'watched'), (False, 'not watched')], default=False, null=True),
        ),
    ]
