# Generated by Django 4.1 on 2024-09-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0004_alter_moviereview_enjoyment_alter_moviereview_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviestatus',
            name='priority',
            field=models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False),
        ),
    ]
