# Generated by Django 4.1 on 2024-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0004_rename_ttconst_availability_tconst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedstatus',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
