# Generated by Django 4.1 on 2024-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0005_watchedstatus_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availability'},
        ),
        migrations.AlterModelOptions(
            name='watcheddates',
            options={'verbose_name_plural': 'Watched Dates'},
        ),
        migrations.AlterModelOptions(
            name='watchedstatus',
            options={'verbose_name_plural': 'Watched Status'},
        ),
        migrations.AlterField(
            model_name='watcheddates',
            name='watch_date',
            field=models.DateField(null=True),
        ),
    ]
