# Generated by Django 4.1 on 2024-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0007_watcheddates_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedstatus',
            name='priority',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
